name: YouTube Facts Automation

on:
  schedule:
    # Run twice daily at 10:00 AM and 5:00 PM UTC
    - cron: '0 10,17 * * *'
  push:
    branches:
      - main
  # Also allow manual trigger
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate facts and create video
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: node generate-video.js
        
      - name: Commit and push if facts database changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add facts_database.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update facts database [automated]"
          git push